## -*- encoding: utf-8 -*-
# This file was *autogenerated* from the file 2016-06-13-150704.sagetex.sage
from sage.all_cmdline import *   # import sage library
_sage_const_269 = Integer(269); _sage_const_2 = Integer(2); _sage_const_1 = Integer(1); _sage_const_0 = Integer(0); _sage_const_131 = Integer(131); _sage_const_336 = Integer(336); _sage_const_2p10 = RealNumber('2.10'); _sage_const_3 = Integer(3); _sage_const_329 = Integer(329); _sage_const_263 = Integer(263); _sage_const_132 = Integer(132); _sage_const_p10 = RealNumber('.10'); _sage_const_1p10 = RealNumber('1.10'); _sage_const_271 = Integer(271)## This file (2016-06-13-150704.sagetex.sage) was *autogenerated* from 2016-06-13-150704.tex with sagetex.sty version 2012/01/16 v2.3.3-69dcb0eb93de.
import sagetex
_st_ = sagetex.SageTeXProcessor('2016-06-13-150704', version='2012/01/16 v2.3.3-69dcb0eb93de', version_check=True)
_st_.blockbegin()
try:
     x = var('x')
     y = var('y')
     step = _sage_const_p10 
     x1 = _sage_const_0 
     x2 = _sage_const_1p10 
     y1 = _sage_const_0 
     y2 =_sage_const_2p10 
 
     output = ""
     output += r"\begin{tikzpicture}[scale=1.0]"
     output += r"\begin{axis}[xmin=%d, xmax=%d, ymin=%d, ymax=%d,grid=major,grid style={dotted},colormap/greenyellow,shader=interp]"%(x1,x2,y1,y2-step)
     output += r"\addplot3[surf,mesh/rows=%d,mesh/cols=%d] coordinates {"%((y2-step-y1)/step+_sage_const_1 ,(x2-step-x1)/step+_sage_const_1  )
     # rows is the number of y values
     for y in srange(y1,y2,step):
         for x in srange(x1,x2,step):
             output += r"(%f, %f, %f) "%(x,y,y)
 
     output += r"};"
     output += r"\end{axis}"
     output += r"\end{tikzpicture}"
except:
 _st_.goboom(_sage_const_131 )
_st_.blockend()
try:
 _st_.inline(_sage_const_0 , output)
except:
 _st_.goboom(_sage_const_132 )
_st_.blockbegin()
try:
     x=var('x')
     y=var('y')
     dydxint = integral(integral(x*y,y,x,_sage_const_1 ),x,_sage_const_0 ,_sage_const_1 )
     dxdyint = integral(integral(x*y,x,_sage_const_0 ,y),y,_sage_const_0 ,_sage_const_1 )
 
     
except:
 _st_.goboom(_sage_const_263 )
_st_.blockend()
try:
 _st_.inline(_sage_const_1 , latex(dydxint))
except:
 _st_.goboom(_sage_const_269 )
try:
 _st_.inline(_sage_const_2 , latex(dydxint))
except:
 _st_.goboom(_sage_const_271 )
_st_.blockbegin()
try:
     x=var('x')
     y=var('y')
     outerint = integral(integral(_sage_const_1 ,y,x,_sage_const_1 -x),x,_sage_const_0 ,_sage_const_1 )
     
except:
 _st_.goboom(_sage_const_329 )
_st_.blockend()
try:
 _st_.inline(_sage_const_3 , latex(outerint))
except:
 _st_.goboom(_sage_const_336 )
_st_.endofdoc()
